Add support for qemu commandline in nova
wmousa/nova pull request #1
Opened 2021-02-14 19:57 UTC by wmousa

2021-02-15 20:07 UTC, moshe010 requested changes

2021-02-15 20:07 UTC, moshe010 commented on nova/tests/unit/virt/libvirt/test_config.py
> +class LibvirtConfigQemuCommandLineTest(LibvirtConfigBaseTest):
can you test for multi-args?

2021-02-15 20:07 UTC, moshe010 commented on nova/virt/libvirt/config.py
> +        for qemu_arg in self.qemu_args:
why do you need the Line 2797-2798. if the list is empty you won't enter it

2021-02-15 20:07 UTC, moshe010 commented on nova/virt/libvirt/driver.py
> +                    args_dict["host_mtu"] = vif["network"]["meta"]["mtu"]
I think the host_mtu is a WA. Please add a note that we need to revisit if it need or not?

2021-02-15 20:07 UTC, moshe010 commented on nova/virt/libvirt/driver.py
> +            if vif.get("vnic_type") in ["virtio-forwarder", "normal", "macvtap"]:
can you check if we can set the alias name? then we can do vdpa0/ vdpa1 which will be less risky code

2021-02-15 21:03 UTC, wmousa commented on nova/tests/unit/virt/libvirt/test_config.py
> +class LibvirtConfigQemuCommandLineTest(LibvirtConfigBaseTest):
done

2021-02-15 21:03 UTC, wmousa commented on nova/virt/libvirt/config.py
> +        for qemu_arg in self.qemu_args:
done

2021-02-15 21:03 UTC, wmousa commented on nova/virt/libvirt/driver.py
> +                    args_dict["host_mtu"] = vif["network"]["meta"]["mtu"]
done

2021-02-15 21:03 UTC, wmousa commented on nova/virt/libvirt/driver.py
> +            if vif.get("vnic_type") in ["virtio-forwarder", "normal", "macvtap"]:
I tried it before it's neglected, the nova code will export xml file without any alias names, I think the qemu is doing it

2021-02-16 10:17 UTC, moshe010 commented
@wmousa  you didn't push new commit

2021-02-17 15:14 UTC, wmousa commented
@moshe010 The code is working fine and tested on a fresh deployment,
As this get merged, I'll open a PR on containerized-ovs project

2021-02-17 17:43 UTC, moshe010 approved these changes

2021-02-17 17:44 UTC, moshe010 commented
@wmousa  I don't have permission to merged but LGTM

2021-02-17 18:12 UTC, merged